//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgeteerApp1 {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The XBee module using socket 9 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.XBee xBee;
        
        /// <summary>The Extender module using socket 11 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Extender extender;
        
        /// <summary>The RS485 module using socket  of extender.</summary>
        private Gadgeteer.Modules.GHIElectronics.RS485 rs485;
        
        /// <summary>The Button module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        /// <summary>The UsbClientSP module using socket 1 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.UsbClientSP usbClientSP;
        
        /// <summary>The Display_T35 module using sockets 14, 13, 12 and 10 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Display_T35 display_T35;
        
        /// <summary>The MulticolorLed module using socket 5 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MulticolorLed multicolorLed;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZSpider Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZSpider)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.xBee = new GTM.GHIElectronics.XBee(9);
            this.extender = new GTM.GHIElectronics.Extender(11);
            this.rs485 = new GTM.GHIElectronics.RS485(this.extender.ExtenderSocketNumber);
            this.button = new GTM.GHIElectronics.Button(4);
            this.usbClientSP = new GTM.GHIElectronics.UsbClientSP(1);
            this.display_T35 = new GTM.GHIElectronics.Display_T35(14, 13, 12, 10);
            this.multicolorLed = new GTM.GHIElectronics.MulticolorLed(5);
        }
    }
}
